# Generated by Django 3.2.1 on 2022-07-30 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0002_accesstype'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_acesso', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='AccessType',
        ),
    ]
