# Generated by Django 3.2.1 on 2022-07-30 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0003_auto_20220730_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_type',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='pessoas.tipoacesso'),
        ),
    ]
