# Generated by Django 3.2.1 on 2023-11-17 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('isbm', models.CharField(max_length=100, verbose_name='ISBM')),
                ('author', models.CharField(max_length=100, verbose_name='Author')),
                ('publisher', models.CharField(max_length=100, verbose_name='Publisher')),
                ('edition', models.IntegerField(verbose_name='Edition')),
                ('pages', models.IntegerField(verbose_name='Number of pages')),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
            ],
        ),
    ]
