# Generated by Django 3.2.1 on 2025-05-17 17:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(default='en', max_length=100, verbose_name='Language'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=7, verbose_name='Price'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='publish_date',
            field=models.DateField(default=datetime.datetime(2025, 5, 17, 17, 38, 19, 7666), verbose_name='Publish Date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
    ]
