# Generated by Django 3.2.1 on 2025-05-15 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20231120_0054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='access_type',
        ),
        migrations.DeleteModel(
            name='AccessType',
        ),
    ]
